include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    invalid_annotation_target: ignore
    missing_required_param: error
    missing_return: error
    record_literal_one_positional_no_trailing_comma: error
  exclude:
    - lib/**/*.g.dart

linter:
  rules:
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - close_sinks
    - prefer_single_quotes
    - lines_longer_than_80_chars
    - directives_ordering
    - combinators_ordering
    - always_declare_return_types
    - always_put_required_named_parameters_first
    - avoid_bool_literals_in_conditional_expressions
    - avoid_equals_and_hash_code_on_mutable_classes
    - avoid_escaping_inner_quotes
    - avoid_implementing_value_types
    - avoid_multiple_declarations_per_line
    - avoid_private_typedef_functions
    - avoid_returning_this
    - avoid_slow_async_io
    - avoid_unused_constructor_parameters
    - cancel_subscriptions
    - cascade_invocations
    - cast_nullable_to_non_nullable
    - eol_at_end_of_file
    - flutter_style_todos
    - implicit_reopen
    - invalid_case_patterns
    - join_return_with_assignment
    - leading_newlines_in_multiline_strings
    - literal_only_boolean_expressions
    - missing_whitespace_between_adjacent_strings
    - no_adjacent_strings_in_list
    - no_literal_bool_comparisons
    - noop_primitive_operations
    - omit_local_variable_types
    - only_throw_errors
    - parameter_assignments
    - prefer_asserts_in_initializer_lists
    - prefer_constructors_over_static_methods
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_null_aware_method_calls
    - always_use_package_imports
    - require_trailing_commas
    - secure_pubspec_urls
    - sized_box_shrink_expand
    - test_types_in_equals
    - throw_in_finally
    - type_literal_in_constant_pattern
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_breaks
    - unnecessary_lambdas
    - unnecessary_null_aware_operator_on_extension_on_nullable
    - unnecessary_null_checks
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - unnecessary_statements
    - unnecessary_to_list_in_spreads
    - unreachable_from_main
    - use_colored_box
    - use_enums
    - use_if_null_to_convert_nulls_to_bools
    - use_is_even_rather_than_modulo
    - use_named_constants
    - use_string_buffers
    - use_super_parameters
    - use_test_throws_matchers
    # Additional rules for Sonarqube
    - avoid_js_rounded_ints
    - avoid_void_async
    - prefer_mixin
